### ISSUE TITLE
How to get real distance for labeled object given an image.

### ISSUE THREAD

**Issue by zhongsheng-chen** [deng232/DINO_SAM_Zoe#1]
Hi Deng, thank you for sharing this code. I am wondering how ZoeDepth convert depth to real distance?

**Comment by deng232** [comment]
I'm not professional in that field and my current project don't have to get exact real distance so I didn't have much research on it. you have to forward this question to ZoeDepth https://github.com/isl-org/ZoeDepth  and they have link for their paper in that. Sorry about that

**Comment by deng232** [comment]
https://github.com/isl-org/ZoeDepth/issues/10#issuecomment-1643770289
" , the model was trained with meters as units for depth. So the output is always supposed to be in meters."

**Comment by deng232** [comment]
> Hi Deng, thank you for sharing this code. I am wondering how ZoeDepth convert depth to real distance?
https://github.com/isl-org/ZoeDepth/issues/10#issuecomment-1643770289
" , the model was trained with meters as units for depth. So the output is always supposed to be in meters."

**Comment by deng232** [comment]
> Hi Deng, thank you for sharing this code. I am wondering how ZoeDepth convert depth to real distance?

https://github.com/isl-org/ZoeDepth/issues/10#issuecomment-1643770289
" , the model was trained with meters as units for depth. So the output is always supposed to be in meters."
